- name: Run Application Playbook
  hosts: [tag_stage_staging]
  roles:
    - { role: common, tags: ["common"] }
    - { role: ansible-role-docker, tags: ["docker"] }

- name:  Install application
  hosts: tag_stage_staging:&tag_component_application
  roles:
    - { role: application, tags: ['application'] }
